# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 20:45
from __future__ import unicode_literals

from django.db import migrations

def add_table_data(apps, schema_editor):
    Table = apps.get_model("utility", "Table")
    for x in range(9):
        Table.objects.create()

    # raise Exception("Boom")

class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_table_data)
    ]
