# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20161020_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
