# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_auto_20161020_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='order',
        ),
        migrations.RemoveField(
            model_name='food',
            name='owner',
        ),
    ]
