# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_food_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utility.Order'),
            preserve_default=False,
        ),
    ]
