# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_auto_20161021_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='user',
            new_name='owner',
        ),
    ]
